"""
UI Configuration and Constants for the Star Trek Tactical Game
"""

# Window dimensions
RIGHT_EVENT_LOG_WIDTH = 300
SHIP_STATUS_WIDTH = 300
ENEMY_SCAN_WIDTH = 280
BOTTOM_PANEL_HEIGHT = 200
STATUS_HEIGHT = 40

# Calculate map size and window dimensions
MAP_SIZE = min(980, 960 - STATUS_HEIGHT - BOTTOM_PANEL_HEIGHT)  # ~720px map
WIDTH = MAP_SIZE + RIGHT_EVENT_LOG_WIDTH + SHIP_STATUS_WIDTH + ENEMY_SCAN_WIDTH
HEIGHT = 1020

# Layout positions
MAP_X = 0
MAP_Y = STATUS_HEIGHT
BOTTOM_PANE_Y = MAP_Y + MAP_SIZE
BOTTOM_PANE_HEIGHT = HEIGHT - BOTTOM_PANE_Y
IMAGE_DISPLAY_WIDTH = MAP_SIZE // 2
CONTROL_PANEL_WIDTH = MAP_SIZE - IMAGE_DISPLAY_WIDTH

# Event log panel
EVENT_LOG_X = MAP_SIZE
EVENT_LOG_Y = STATUS_HEIGHT
EVENT_LOG_WIDTH = RIGHT_EVENT_LOG_WIDTH
EVENT_LOG_HEIGHT = HEIGHT - STATUS_HEIGHT

# Ship status panel
SHIP_STATUS_X = MAP_SIZE + EVENT_LOG_WIDTH
SHIP_STATUS_Y = STATUS_HEIGHT
SHIP_STATUS_HEIGHT = HEIGHT - STATUS_HEIGHT

# Enemy scan panel
ENEMY_SCAN_X = MAP_SIZE + RIGHT_EVENT_LOG_WIDTH + SHIP_STATUS_WIDTH
ENEMY_SCAN_Y = STATUS_HEIGHT
ENEMY_SCAN_HEIGHT = HEIGHT - STATUS_HEIGHT

# Colors
COLOR_BG = (20, 20, 30)
COLOR_STATUS = (60, 60, 100)
COLOR_MAP = (40, 40, 60)
COLOR_EVENT_LOG = (30, 30, 50)
COLOR_EVENT_LOG_BORDER = (80, 80, 120)
COLOR_IMAGE_DISPLAY = (30, 50, 30)
COLOR_CONTROL_PANEL = (50, 30, 30)
COLOR_BUTTON_AREA_BORDER = (80, 50, 50)
COLOR_TEXT = (220, 220, 220)
HEX_OUTLINE = (180, 180, 220)
HEX_BG = (40, 40, 60)
COLOR_MAP_DEBUG = (255, 0, 0)
COLOR_GRID_DEBUG = (0, 255, 0)

# Button panel parameters
BUTTON_W = 110
BUTTON_H = 35
BUTTON_GAP = 15
TOGGLE_BTN_W = 130
TOGGLE_BTN_H = 35
BUTTON_COLOR = (100, 100, 180)

# Game settings
FPS = 30
EVENT_LOG_MAX_LINES = 25

# Hex grid settings
HEX_GRID_COLS = 20
HEX_GRID_ROWS = 20

# Animation settings
PHASER_ANIMATION_DURATION = 1.0